spring.application.name=barberia
server.port=8095
spring.datasource.url=jdbc:sqlite:./data/barberia.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
application.security.jwt.secret-key=miClaveSecretaMuySeguraQueEsLoSuficientementeLarga
application.security.jwt.expiration=3600000
application.security.jwt.refresh-token.expiration=86400000

# WasenderAPI (WhatsApp)
wasenderapi.api-key=fc907f08872c83a3a4f78ee2713af09cf4f131ad235c2f2cf05c85f4e753faf4
wasenderapi.api-url=https://www.wasenderapi.com/api/send-message