name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Update Backend
        run: |
          cd /var/www/barberia/backend

          git reset --hard
          git pull origin main

      - name: Build Backend
        run: |
          cd /var/www/barberia/backend

          chmod +x mvnw

          ./mvnw clean package -DskipTests

      - name: Restart Spring
        run: |
          sudo systemctl restart barberia-backend.service
